In [20]:
# Analyse the JSOn that is being created
import json
import pandas as pd

with open('reddit_data_v2.json') as f:
    data = json.load(f)

data_df = pd.DataFrame(data)

In [21]:
data_df.head

<bound method NDFrame.head of          Type  Post_id                                         Title  \
0        Post  1bkgpz3               How I made $21k on Side Hustles
1     Comment  1bkgpz3               How I made $21k on Side Hustles
2     Comment  1bkgpz3               How I made $21k on Side Hustles
3     Comment  1bkgpz3               How I made $21k on Side Hustles
4     Comment  1bkgpz3               How I made $21k on Side Hustles
...       ...      ...                                           ...
5174  Comment  1g5wgwm  How I'm Making $8-9k a month Posting Content
5175  Comment  1g5wgwm  How I'm Making $8-9k a month Posting Content
5176  Comment  1g5wgwm  How I'm Making $8-9k a month Posting Content
5177  Comment  1g5wgwm  How I'm Making $8-9k a month Posting Content
5178  Comment  1g5wgwm  How I'm Making $8-9k a month Posting Content

                   Author            Timestamp  \
0           Kamikaze_Cash         1711053341.0
1           PlantZaddyPHL  2024-03-21T23:10:27
2                 Unknown  2024-03-21T23:46:06
3      Jimmydontcrackcorn  2024-03-21T23:17:18
4          DreamBenchMark  2024-03-21T22:42:40
...                   ...                  ...
5174  MakeTheRightChoice_  2024-10-17T21:59:05
5175             Stiddy13  2024-10-17T21:34:05
5176  MakeTheRightChoice_  2024-10-17T21:37:44
5177             Stiddy13  2024-10-17T22:26:23
5178  MakeTheRightChoice_  2024-10-17T22:27:03

                                                   Text  Score  \
0     After my last couple comments on r/sidehustle ...   4898
1     This is the single most useful post I've seen ...    914
2                                             [removed]    309
3     Love your YouTube videos too man you’ll have t...     69
4     Amazing, your side hustling sounds like a full...     44
...                                                 ...    ...
5174  Thank you for educating me with a thorough res...      3
5175  I mean sure if you create your own content the...      4
5176  Indeed. I guess the money making part comes fr...      0
5177  OP isn’t creating their own content. I think t...      2
5178                    I see. Twas too good to be true      1

      Total_comments                                           Post_URL
0                591  https://www.reddit.com/r/sidehustle/comments/1...
1                  0                                               None
2                  0                                               None
3                  0                                               None
4                  0                                               None
...              ...                                                ...
5174               0                                               None
5175               0                                               None
5176               0                                               None
5177               0                                               None
5178               0                                               None

[5179 rows x 9 columns]>

In [22]:
data_df[data_df['Type'] == 'Comment'].groupby('Post_id').count()

         Type  Title  Author  Timestamp  Text  Score  Total_comments  Post_URL
Post_id
15qrqo0   892    892     892        892   892    892             892         0
1649oau  1167   1167    1167       1167  1167   1167            1167         0
16mh2fv  1043   1043    1043       1043  1043   1043            1043         0
1bezveu   413    413     413        413   413    413             413         0
1bkgpz3   487    487     487        487   487    487             487         0
1dajevb   316    316     316        316   316    316             316         0
1dis4ex   322    322     322        322   322    322             322         0
1e9ooqz   185    185     185        185   185    185             185         0
1g3h24s   205    205     205        205   205    205             205         0
1g5wgwm   139    139     139        139   139    139             139         0

In [23]:
data_df[data_df['Type'] == 'Post']

,Type,Post_id,Title,Author,Timestamp,Text,Score,Total_comments,Post_URL
0,Post,1bkgpz3,How I made $21k on Side Hustles,Kamikaze_Cash,1711053341.0,After my last couple comments on r/sidehustle ...,4898,591,https://www.reddit.com/r/sidehustle/comments/1...
488,Post,1g3h24s,How I accidentally made 80k USD with a simple ...,Available-Resort-951,1728916015.0,Hey everyone! I thought I’d share a fun and un...,3447,254,https://www.reddit.com/r/sidehustle/comments/1...
694,Post,1e9ooqz,Feeling so proud of my extra $200 a month,Unknown,1721680524.0,Despite all of the advice saying NOT to do dig...,2542,230,https://www.reddit.com/r/sidehustle/comments/1...
880,Post,1dis4ex,My $300/month hustle,Heartsov,1718721146.0,I started an Instagram page a couple years ago...,1845,392,https://www.reddit.com/r/sidehustle/comments/1...
1203,Post,16mh2fv,What's Your Most Unexpectedly Profitable Side ...,wademarketing,1695096885.0,Hey everyone! Have you ever stumbled upon a s...,1610,1750,https://www.reddit.com/r/sidehustle/comments/1...
2247,Post,1649oau,What are some realistic ways to make $500-$100...,lil-freshiee,1693287531.0,I see a lot of ideas for side hustles and I un...,1456,1468,https://www.reddit.com/r/sidehustle/comments/1...
3415,Post,1bezveu,Posted this in another sub and it blew up. I m...,Mattsfloored,1710460062.0,"I first learned about Churning last year, and ...",1334,461,https://www.reddit.com/r/sidehustle/comments/1...
3829,Post,15qrqo0,What's your most unique side hustle that you n...,wademarketing,1692011541.0,"Hey, have you ever had a side hustle that turn...",1038,1082,https://www.reddit.com/r/sidehustle/comments/1...
4722,Post,1dajevb,Painting Curbs is so lucrative($100/hr),Medinarunner,1717788333.0,Just made $300 in about 3hrs. Start ups cost a...,1037,323,https://www.reddit.com/r/sidehustle/comments/1...
5039,Post,1g5wgwm,How I'm Making $8-9k a month Posting Content,trevorbfoster,1729186335.0,"Hey all, \n\nWanted to share the rather low ef...",1037,158,https://www.reddit.com/r/sidehustle/comments/1...

In [ ]:
# Create LDA topic model out of all the texts